apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchdeployment
  labels:
    team: blalba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service    
  template:
    metadata:
      labels:
        app: search-service 
    spec:
      containers:        
        - image: ysfyrdmcl/shopss:v001
          name:  podsearch
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 7071      

 