apiVersion: v1

kind: Service

metadata:
  name: loadbalancer-management

spec:
  selector:
    app: management-service

  type: LoadBalancer

  ports:
    - name: management-service

      port: 7070

      targetPort: 7070
